### ISSUE TITLE
Cannot Get preference dataset and checkpoints

### ISSUE THREAD

**Issue by shun31y** [THU-LYJ-Lab/InstructMotion#2]
Thank you for your great works in HumanMotionGeneration.
I want to run this code, but I can't get the preference dataset and checkpoints cause I'm not Chinese and Baidu user.(Now, foreigner isn't allowed to register at Baidu)
Could you give me other link(such as google drive) for downloading preference dataset and checkpoints?

**Comment by jsheng112** [comment]
We apologize for the inconvenience. I have updated the readme with another link to download the datasets.

**Comment by shun31y** [comment]
thanks!!!
